### ISSUE TITLE
LICENSE File

### ISSUE THREAD

**Issue by mjcarroll** [netbot-tamu/MFG#1]
It would be helpful if there was a top-level LICENSE file for the project.

**Comment by mjcarroll** [comment]
Sorry, I just found the License in some of the headers, but it may still be useful to add a top-level LICENSE file to the repository.

**Comment by netbot-tamu** [comment]
Thanks. We will do it.

-Dez

Dezhen Song, Ph.D., Associate Professor

Department of Computer Science and Engineering,

311B HRBB, TAMU 3112,

Texas A&M University,

College Station, TX 77843-3112

Phone +1(979)8455464

 http://faculty.cs.tamu.edu/dzsong http://faculty.cs.tamu.edu/dzsong

**Comment by netbot-tamu** [comment]
Thanks!
